### ISSUE TITLE
How to use justlazy to load images in a tab only when tab is active?

### ISSUE THREAD

**Issue by ladygh** [fhopeman/justlazy#10]
Sorry for this stupid question, I just started to learn js and css.

                        <div>
                            <ul class="list">
                                <li class="item" >
                                    <a class="td-subcat-link" href="#">All</a>
                                </li>
                                <li class="item" >
                                    <a class="td-subcat-link" href="#">Auto Shows</a>
                                </li></ul>
                          </div>
                          <div class="td_block_inner">
                                <div><img src="1.jpg"></img></div>
                                <div display="none"><img src="2.jpg"></img></div>
                         </div></div>
By default, when I laod the page, all images will be loaded. How can I use justlazy to loay images only when the tab is active?

Thanks

**Comment by fhopeman** [comment]
Hi,

I would suggest, that you define a placeholder for each image, e.g. for the first image:
```
<span id="imageOne" data-src="1.jpg" data-alt="image one"
      data-title="title of image one"
      class="justlazy-spinner">
</span>
```
Then you have to add an event listener to your tab button which calls `Justlazy.lazyLoad(document.getElementById('imageOne'))`. This is the same like the custom load example in the documentation (http://fhopeman.github.io/justlazy/#example-by-custom-event).

If that works, you can improve your code. E.g. use classes for all placeholders in a specific tab and initialize them in a loop.
