### ISSUE TITLE
Browserify

### ISSUE THREAD

**Issue by anthonyjfio** [fhopeman/justlazy#2]
Could you provide an example using browserify?

I cannot seem to get it to work, but it could just be me

Thank you

**Comment by fhopeman** [comment]
Sure, I have build up a simple demo application which uses browserify:

##### package.json
```
{
  "name": "browserify-it",
  "version": "1.0.0",
  "description": "test to browserify justlazy",
  "main": "js/main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "fhopeman",
  "license": "MIT",
  "dependencies": {
    "browserify": "~12.0.1",
    "justlazy": "~1.3.0"
  }
}
```

##### js/main.js
```
var justlazy = require("justlazy");

console.log("you have the following possibilities to lazy load images:");
console.log(justlazy);
```

##### index.html
```
<h1>browserify demo</h1>
<script src="js/all.js"></script>
```

With this setup you can run `npm install` and then the browserify command:
```
./node_modules/browserify/bin/cmd.js js/main.js -o js/all.js
```

Now, you have a browserified file `all.js` which prints the `justlazy` functions to the console.
