### ISSUE TITLE
add option to keep defined attributes of the placeholder

### ISSUE THREAD

**Issue by fhopeman** [fhopeman/justlazy#4]
In some cases users need to set attributes (e.g. class or data-*) of the placeholder and want to keep them after the replacement of the placeholer.

**Comment by roura356a** [comment]
+1 I need a way to add a class to the newly generated img element.

**Comment by roura356a** [comment]
Hi @fhopeman, I submitted a PR adding support for this, so if you write a data-class attribute, the newly generated img element will have that class. This attribute is optional in order to be backwards compatible, so we don't need to push the version to 2.0 only for this.

**Comment by roura356a** [comment]
Ok, looks fine to me. Although the feature I added in my opinion is a must-have, your solution also solves this problem.

**Comment by fhopeman** [comment]
I've implemented a new hook, which is more suitable for your case.

Check out the new `onreplaceCallback`, which is invoked immediately before the image is replaced. I've updated the documentation and changed the examples (http://fhopeman.github.io/justlazy/#demo).
